-- Seed data: Gym exercises
insert into exercises (name, instructions, benefits, muscle_groups, equipment, category, video_url) values

-- CHEST
('Barbell bench press', 'Lie on a flat bench, grip the bar slightly wider than shoulder-width, lower it to your mid-chest, then press back up to full arm extension.', 'Builds overall chest mass and pressing strength, with secondary work for shoulders and triceps.', ARRAY['chest'], ARRAY['barbell']::text[], 'gym', null),
('Incline dumbbell press', 'Set a bench to a 30-45 degree incline, press dumbbells from shoulder height to full extension above your upper chest.', 'Targets the upper chest more than a flat press, improving overall chest shape and strength.', ARRAY['chest'], ARRAY['dumbbell']::text[], 'gym', null),
('Decline bench press', 'Lie on a decline bench, lower the bar to your lower chest, then press back to full extension.', 'Emphasizes the lower chest fibers for balanced chest development.', ARRAY['chest'], ARRAY['barbell']::text[], 'gym', null),
('Dumbbell flyes', 'Lie on a flat bench holding dumbbells above your chest with a slight elbow bend, lower them out to the sides in an arc, then bring them back together.', 'Stretches and isolates the chest muscles for improved definition.', ARRAY['chest'], ARRAY['dumbbell']::text[], 'gym', null),
('Cable crossover', 'Stand between two cable towers, pull the handles down and across your body in an arc until your hands meet in front of you.', 'Keeps constant tension on the chest through the full range of motion.', ARRAY['chest'], ARRAY['cable machine']::text[], 'gym', null),
('Chest press machine', 'Sit in the machine, grip the handles at chest height, and press forward until your arms are extended, then return slowly.', 'A beginner-friendly way to build chest strength with controlled movement.', ARRAY['chest'], ARRAY['machine']::text[], 'gym', null),
('Pec deck machine', 'Sit with your back against the pad, arms bent at the handles, and bring your arms together in front of your chest.', 'Isolates the chest with minimal shoulder and triceps involvement.', ARRAY['chest'], ARRAY['machine']::text[], 'gym', null),
('Dips (chest-focused)', 'Lean your torso forward on the dip bars and lower your body until your upper arms are parallel to the floor, then press back up.', 'Builds chest and triceps strength using bodyweight resistance.', ARRAY['chest', 'triceps'], ARRAY['dip bars']::text[], 'gym', null),

-- BACK
('Pull-ups', 'Hang from a bar with an overhand grip, pull your body up until your chin clears the bar, then lower with control.', 'Builds back width and grip strength using bodyweight resistance.', ARRAY['back'], ARRAY['pull-up bar']::text[], 'gym', null),
('Lat pulldown', 'Sit at the machine, grip the bar wider than shoulder-width, and pull it down to your upper chest, then control it back up.', 'A pull-up alternative that builds back width for those still working toward bodyweight pull-ups.', ARRAY['back'], ARRAY['cable machine']::text[], 'gym', null),
('Barbell bent-over row', 'Hinge at the hips with a flat back, pull the bar toward your lower ribs, then lower it back down.', 'Builds back thickness and improves posture-supporting muscles.', ARRAY['back'], ARRAY['barbell']::text[], 'gym', null),
('Single-arm dumbbell row', 'Support one knee and hand on a bench, row the dumbbell up toward your hip with the other arm.', 'Allows a full range of motion per side and helps correct muscle imbalances.', ARRAY['back'], ARRAY['dumbbell']::text[], 'gym', null),
('Seated cable row', 'Sit at the machine with knees slightly bent, pull the handle toward your torso while keeping your back straight.', 'Builds mid-back thickness with controlled, joint-friendly resistance.', ARRAY['back'], ARRAY['cable machine']::text[], 'gym', null),
('T-bar row', 'Straddle the T-bar with a slight forward hinge, pull the handle up toward your chest, then lower with control.', 'Builds back thickness with a strong contraction at the top of the movement.', ARRAY['back'], ARRAY['t-bar machine']::text[], 'gym', null),
('Back extension', 'Position your hips on the pad of a hyperextension bench, lower your torso forward, then raise back up to a straight line.', 'Strengthens the lower back and supports overall spinal health.', ARRAY['back'], ARRAY['hyperextension bench']::text[], 'gym', null),
('Assisted pull-up machine', 'Kneel on the pad, grip the handles, and pull yourself up as the machine offsets part of your bodyweight.', 'Builds toward unassisted pull-ups by scaling the resistance.', ARRAY['back'], ARRAY['machine']::text[], 'gym', null),

-- SHOULDERS
('Overhead barbell press', 'Stand holding the bar at shoulder height, press it overhead until your arms are fully extended, then lower with control.', 'Builds overall shoulder strength and size, with core stability benefits.', ARRAY['shoulders'], ARRAY['barbell']::text[], 'gym', null),
('Dumbbell shoulder press', 'Sit or stand holding dumbbells at shoulder height, press them overhead, then lower back down.', 'Allows a more natural pressing path than a barbell, reducing shoulder strain.', ARRAY['shoulders'], ARRAY['dumbbell']::text[], 'gym', null),
('Arnold press', 'Start with dumbbells in front of your shoulders palms facing you, rotate and press overhead as your palms turn forward.', 'Works the shoulders through a fuller range of motion than a standard press.', ARRAY['shoulders'], ARRAY['dumbbell']::text[], 'gym', null),
('Lateral raises', 'Hold dumbbells at your sides, raise them out to shoulder height with a slight elbow bend, then lower with control.', 'Builds shoulder width by targeting the side deltoids.', ARRAY['shoulders'], ARRAY['dumbbell']::text[], 'gym', null),
('Front raises', 'Hold dumbbells in front of your thighs, raise them forward to shoulder height, then lower back down.', 'Targets the front deltoids for balanced shoulder development.', ARRAY['shoulders'], ARRAY['dumbbell']::text[], 'gym', null),
('Rear delt flyes', 'Hinge forward at the hips holding dumbbells, raise them out to the sides while keeping a slight elbow bend.', 'Strengthens the rear shoulders, improving posture and shoulder balance.', ARRAY['shoulders'], ARRAY['dumbbell']::text[], 'gym', null),
('Face pulls', 'Set a cable at head height, pull the rope toward your face while flaring your elbows out.', 'Improves shoulder health and posture by strengthening the rear delts and upper back.', ARRAY['shoulders'], ARRAY['cable machine']::text[], 'gym', null),
('Upright row', 'Hold a barbell or dumbbells in front of your thighs, pull it up toward your chin while keeping it close to your body.', 'Builds shoulder and trap strength together.', ARRAY['shoulders'], ARRAY['barbell']::text[], 'gym', null),
('Shrugs', 'Hold dumbbells or a barbell at your sides, raise your shoulders straight up toward your ears, then lower.', 'Targets the trapezius muscles for a stronger, more stable upper back.', ARRAY['shoulders'], ARRAY['dumbbell']::text[], 'gym', null),
('Shoulder press machine', 'Sit in the machine, grip the handles at shoulder height, and press upward until arms are extended.', 'A stable, guided way to build shoulder strength.', ARRAY['shoulders'], ARRAY['machine']::text[], 'gym', null),

-- BICEPS
('Barbell curl', 'Stand holding a barbell with an underhand grip, curl it up toward your shoulders, then lower with control.', 'A classic mass-builder for the biceps.', ARRAY['biceps'], ARRAY['barbell']::text[], 'gym', null),
('Dumbbell curl', 'Hold dumbbells at your sides, curl them up toward your shoulders one at a time or together, then lower.', 'Allows independent arm movement to address any strength imbalances.', ARRAY['biceps'], ARRAY['dumbbell']::text[], 'gym', null),
('Hammer curl', 'Hold dumbbells with a neutral (palms-facing-in) grip, curl them up toward your shoulders.', 'Targets the biceps and forearms together.', ARRAY['biceps'], ARRAY['dumbbell']::text[], 'gym', null),
('Preacher curl', 'Rest your arms on a preacher bench pad, curl the weight up toward your shoulders, then lower with control.', 'Isolates the biceps by removing momentum from the movement.', ARRAY['biceps'], ARRAY['barbell']::text[], 'gym', null),
('Cable curl', 'Stand facing a low cable pulley, curl the handle up toward your shoulders, then lower with control.', 'Keeps constant tension on the biceps throughout the movement.', ARRAY['biceps'], ARRAY['cable machine']::text[], 'gym', null),
('Concentration curl', 'Sit with your elbow braced against your inner thigh, curl the dumbbell up toward your shoulder.', 'Isolates one bicep at a time for a strong peak contraction.', ARRAY['biceps'], ARRAY['dumbbell']::text[], 'gym', null),
('EZ-bar curl', 'Hold the angled EZ-bar with an underhand grip, curl it up toward your shoulders, then lower.', 'Reduces wrist strain compared to a straight barbell while still building bicep mass.', ARRAY['biceps'], ARRAY['ez-bar']::text[], 'gym', null),

-- TRICEPS
('Tricep pushdown', 'Stand facing a cable machine, push the attachment down until your arms are fully extended, then return with control.', 'Isolates the triceps for arm size and pressing strength.', ARRAY['triceps'], ARRAY['cable machine']::text[], 'gym', null),
('Overhead tricep extension', 'Hold a dumbbell overhead with both hands, lower it behind your head, then extend back up.', 'Targets the long head of the triceps for overall arm size.', ARRAY['triceps'], ARRAY['dumbbell']::text[], 'gym', null),
('Skull crushers', 'Lie on a bench holding a barbell above your chest, lower it toward your forehead by bending your elbows, then extend back up.', 'Builds triceps mass with a strong stretch at the bottom.', ARRAY['triceps'], ARRAY['barbell']::text[], 'gym', null),
('Close-grip bench press', 'Lie on a bench and press a barbell using a shoulder-width or narrower grip.', 'Combines chest and tricep work with a heavier pressing movement.', ARRAY['triceps', 'chest'], ARRAY['barbell']::text[], 'gym', null),
('Dips (tricep-focused)', 'Keep your torso upright on the dip bars, lower until your elbows reach about 90 degrees, then press back up.', 'Builds tricep strength and size using bodyweight resistance.', ARRAY['triceps'], ARRAY['dip bars']::text[], 'gym', null),
('Tricep kickbacks', 'Hinge forward holding a dumbbell with your upper arm parallel to the floor, extend your forearm back, then return.', 'Isolates the triceps with a strong end-range contraction.', ARRAY['triceps'], ARRAY['dumbbell']::text[], 'gym', null),

-- QUADS
('Barbell back squat', 'Rest the bar across your upper back, squat down until your thighs are parallel to the floor, then drive back up.', 'A foundational lower-body exercise that builds overall leg strength and size.', ARRAY['quadriceps'], ARRAY['barbell']::text[], 'gym', null),
('Front squat', 'Rest the bar across the front of your shoulders, squat down keeping your torso upright, then stand back up.', 'Emphasizes the quads more than a back squat while also building core strength.', ARRAY['quadriceps'], ARRAY['barbell']::text[], 'gym', null),
('Leg press', 'Sit in the machine, place your feet on the platform, and press it away by extending your legs, then return with control.', 'Builds leg strength with a supported back, reducing spinal load.', ARRAY['quadriceps'], ARRAY['machine']::text[], 'gym', null),
('Leg extension', 'Sit in the machine with your legs under the pad, extend your knees to lift the pad, then lower with control.', 'Isolates the quads directly for targeted strength and definition.', ARRAY['quadriceps'], ARRAY['machine']::text[], 'gym', null),
('Hack squat', 'Position yourself in the hack squat machine, lower into a squat, then press back up through your heels.', 'Builds quad strength with a fixed, supported movement path.', ARRAY['quadriceps'], ARRAY['machine']::text[], 'gym', null),
('Bulgarian split squat', 'Rest one foot behind you on a bench, lower your body until your front thigh is parallel to the floor, then push back up.', 'Builds single-leg strength and helps correct imbalances between legs.', ARRAY['quadriceps'], ARRAY['dumbbell']::text[], 'gym', null),
('Walking lunges', 'Step forward into a lunge, lowering your back knee toward the floor, then bring your rear leg through into the next step.', 'Builds leg strength while also challenging balance and coordination.', ARRAY['quadriceps'], ARRAY['dumbbell']::text[], 'gym', null),
('Goblet squat', 'Hold a dumbbell close to your chest, squat down between your knees, then stand back up.', 'A beginner-friendly squat variation that reinforces good squat form.', ARRAY['quadriceps'], ARRAY['dumbbell']::text[], 'gym', null),

-- HAMSTRINGS & GLUTES
('Romanian deadlift', 'Hold a barbell in front of your thighs, hinge at the hips while keeping legs mostly straight, lower the bar, then return to standing.', 'Builds hamstring and glute strength while improving hip hinge mechanics.', ARRAY['hamstrings'], ARRAY['barbell']::text[], 'gym', null),
('Leg curl', 'Lie face down or sit in the machine, curl your heels toward your glutes, then lower with control.', 'Isolates the hamstrings for balanced leg development.', ARRAY['hamstrings'], ARRAY['machine']::text[], 'gym', null),
('Hip thrust', 'Rest your upper back on a bench with a barbell across your hips, drive your hips up until your body forms a straight line, then lower.', 'One of the most effective glute-building exercises.', ARRAY['glutes'], ARRAY['barbell']::text[], 'gym', null),
('Glute bridge', 'Lie on your back with knees bent, drive your hips up by squeezing your glutes, then lower with control.', 'Builds glute strength and can be done with just bodyweight or added resistance.', ARRAY['glutes'], ARRAY[]::text[], 'gym', null),
('Cable pull-through', 'Face away from a low cable, hinge at the hips to reach between your legs, then drive your hips forward to standing.', 'Reinforces the hip hinge pattern while building glutes and hamstrings.', ARRAY['glutes', 'hamstrings'], ARRAY['cable machine']::text[], 'gym', null),
('Good mornings', 'Rest a barbell across your upper back, hinge forward at the hips with a flat back, then return to standing.', 'Strengthens the hamstrings, glutes, and lower back together.', ARRAY['hamstrings'], ARRAY['barbell']::text[], 'gym', null),
('Glute kickback', 'Using a cable or machine, kick one leg back and up while keeping your core braced, then return with control.', 'Isolates the glutes with a strong contraction at the top.', ARRAY['glutes'], ARRAY['cable machine']::text[], 'gym', null),

-- CALVES
('Standing calf raise', 'Stand on the balls of your feet on a raised platform, rise up onto your toes, then lower your heels below the platform.', 'Builds calf size and strength for better lower-leg power.', ARRAY['calves'], ARRAY['machine']::text[], 'gym', null),
('Seated calf raise', 'Sit with the balls of your feet on a platform and weight across your knees, raise your heels, then lower.', 'Targets the calves from a seated angle for balanced development.', ARRAY['calves'], ARRAY['machine']::text[], 'gym', null),
('Calf press on leg press', 'Using the leg press machine, place the balls of your feet on the platform and press through your toes.', 'Builds calf strength using a machine already common in most gyms.', ARRAY['calves'], ARRAY['machine']::text[], 'gym', null),

-- ABS / CORE
('Plank', 'Hold your body in a straight line supported on your forearms and toes, keeping your core braced.', 'Builds core stability and endurance without any equipment.', ARRAY['core'], ARRAY[]::text[], 'gym', null),
('Crunches', 'Lie on your back with knees bent, curl your shoulders up toward your knees, then lower with control.', 'A classic core exercise for building abdominal strength.', ARRAY['core'], ARRAY[]::text[], 'gym', null),
('Hanging leg raises', 'Hang from a bar, raise your legs up toward your chest while keeping them straight, then lower with control.', 'Builds strong lower abs and grip strength together.', ARRAY['core'], ARRAY['pull-up bar']::text[], 'gym', null),
('Cable woodchoppers', 'Set a cable at high or low position, rotate your torso to pull the handle diagonally across your body.', 'Builds rotational core strength useful for many sports and daily movements.', ARRAY['core'], ARRAY['cable machine']::text[], 'gym', null),
('Russian twists', 'Sit with knees bent and torso leaned back slightly, rotate a weight from side to side across your body.', 'Targets the obliques for rotational core strength.', ARRAY['core'], ARRAY['dumbbell']::text[], 'gym', null),
('Ab wheel rollout', 'Kneel holding an ab wheel, roll it forward as far as you can control, then pull back to the starting position.', 'One of the most challenging core exercises, building serious core strength.', ARRAY['core'], ARRAY['ab wheel']::text[], 'gym', null),
('Sit-ups', 'Lie on your back with knees bent, curl your entire torso up to a seated position, then lower back down.', 'Builds abdominal strength through a fuller range of motion than a crunch.', ARRAY['core'], ARRAY[]::text[], 'gym', null),
('Cable crunch', 'Kneel facing a high cable, crunch your torso down while holding the rope behind your head.', 'Allows progressive overload on the abs beyond bodyweight crunches.', ARRAY['core'], ARRAY['cable machine']::text[], 'gym', null),
('Decline bench sit-ups', 'Secure your feet on a decline bench, lower your torso back, then curl back up to sitting.', 'Increases the difficulty of a standard sit-up for more advanced core training.', ARRAY['core'], ARRAY['bench']::text[], 'gym', null),

-- FULL-BODY / OLYMPIC LIFTS
('Clean and jerk', 'Lift the bar from the floor to your shoulders in one motion, then drive it overhead with a leg dip and press.', 'A full-body power and strength movement used in competitive weightlifting.', ARRAY['back', 'quadriceps', 'shoulders'], ARRAY['barbell']::text[], 'gym', null),
('Snatch', 'Lift the bar from the floor to overhead in one continuous motion, catching it in a squat position.', 'Builds explosive full-body power and coordination.', ARRAY['back', 'shoulders', 'quadriceps'], ARRAY['barbell']::text[], 'gym', null),
('Kettlebell swing', 'Hinge at the hips to swing the kettlebell between your legs, then drive your hips forward to swing it to shoulder height.', 'Builds explosive hip power and cardiovascular conditioning together.', ARRAY['glutes', 'hamstrings'], ARRAY['kettlebell']::text[], 'gym', null),
('Farmers carry', 'Hold a heavy weight in each hand and walk a set distance while keeping your posture upright.', 'Builds grip strength, core stability, and overall conditioning.', ARRAY['back', 'core'], ARRAY['dumbbell']::text[], 'gym', null),
('Thruster', 'Hold weights at your shoulders, squat down, then drive up and press the weights overhead in one motion.', 'Combines a squat and press for an efficient full-body, high-intensity movement.', ARRAY['quadriceps', 'shoulders'], ARRAY['dumbbell']::text[], 'gym', null),
('Burpees', 'Drop into a squat, kick your feet back into a plank, do a push-up, jump your feet back in, then jump up.', 'A high-intensity full-body movement that builds strength and cardiovascular fitness together.', ARRAY['cardiovascular system'], ARRAY[]::text[], 'gym', null),

-- CARDIO MACHINES
('Treadmill running', 'Set your desired speed and incline, and run or walk while maintaining good posture.', 'Builds cardiovascular endurance and burns calories.', ARRAY['cardiovascular system'], ARRAY['treadmill']::text[], 'gym', null),
('Stationary bike', 'Adjust the seat to your height and pedal at a steady or interval pace.', 'A joint-friendly way to build cardiovascular fitness.', ARRAY['cardiovascular system'], ARRAY['stationary bike']::text[], 'gym', null),
('Rowing machine', 'Drive through your legs, lean back slightly, then pull the handle to your chest, and reverse the motion smoothly.', 'Combines cardio with full-body strength work in a single movement.', ARRAY['cardiovascular system', 'back'], ARRAY['rowing machine']::text[], 'gym', null),
('Elliptical', 'Stand on the pedals and move your legs and arms in a smooth, continuous motion.', 'A low-impact way to build cardiovascular endurance.', ARRAY['cardiovascular system'], ARRAY['elliptical']::text[], 'gym', null),
('Stair climber', 'Step continuously as the machine steps move beneath you, maintaining an upright posture.', 'Builds cardiovascular fitness and lower-body endurance.', ARRAY['cardiovascular system', 'quadriceps'], ARRAY['stair climber']::text[], 'gym', null),
('Assault bike', 'Pedal while pushing and pulling the handles, adjusting intensity based on your effort.', 'Delivers a high-intensity, full-body cardio workout.', ARRAY['cardiovascular system'], ARRAY['assault bike']::text[], 'gym', null);
