import { useAudioPlayer, useAudioPlayerStatus } from 'expo-audio';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { dark } from '../lib/theme';

// All three tracks are synthesized noise generated by
// scripts/generate_ambient_noise.js (Voss-McCartney pink noise, a
// leaky-integrator brown noise, and a layered hiss-over-pink "rain"
// texture) -- pure DSP, no licensed audio samples.
const TRACKS = [
  { key: 'pink', label: 'Pink Noise', emoji: '🌸', asset: require('../assets/audio/pink_noise.wav') },
  { key: 'brown', label: 'Brown Noise', emoji: '🟤', asset: require('../assets/audio/brown_noise.wav') },
  { key: 'rain', label: 'Rain (Ambient)', emoji: '🌧️', asset: require('../assets/audio/rain_ambient.wav') },
] as const;

type TrackKey = (typeof TRACKS)[number]['key'];

function TrackButton({
  label,
  emoji,
  asset,
  onPlayingChange,
  activeKey,
  myKey,
}: {
  label: string;
  emoji: string;
  asset: number;
  onPlayingChange: (key: TrackKey, playing: boolean) => void;
  activeKey: TrackKey | null;
  myKey: TrackKey;
}) {
  const player = useAudioPlayer(asset);
  const status = useAudioPlayerStatus(player);

  useEffect(() => {
    player.loop = true;
  }, [player]);

  // Another track was selected -- stop this one.
  useEffect(() => {
    if (activeKey !== myKey && status.playing) {
      player.pause();
      player.seekTo(0);
    }
  }, [activeKey, myKey, player, status.playing]);

  const toggle = () => {
    if (status.playing) {
      player.pause();
      onPlayingChange(myKey, false);
    } else {
      player.play();
      onPlayingChange(myKey, true);
    }
  };

  const isActive = activeKey === myKey && status.playing;

  return (
    <Pressable style={[styles.trackButton, isActive && styles.trackButtonActive]} onPress={toggle}>
      <Text style={styles.trackEmoji}>{emoji}</Text>
      <Text style={[styles.trackLabel, isActive && styles.trackLabelActive]}>{label}</Text>
      <Text style={styles.trackState}>{isActive ? '⏸ Playing' : '▶ Play'}</Text>
    </Pressable>
  );
}

export default function SleepAmbientNoise() {
  const [activeKey, setActiveKey] = useState<TrackKey | null>(null);

  return (
    <View style={styles.card}>
      <Text style={styles.title}>🎧 Ambient Noise</Text>
      <View style={styles.tracksRow}>
        {TRACKS.map((t) => (
          <TrackButton
            key={t.key}
            label={t.label}
            emoji={t.emoji}
            asset={t.asset}
            activeKey={activeKey}
            myKey={t.key}
            onPlayingChange={(key, playing) => setActiveKey(playing ? key : null)}
          />
        ))}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    borderWidth: 1,
    borderColor: dark.border,
    backgroundColor: dark.surface,
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
  },
  title: {
    color: dark.text,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 12,
  },
  tracksRow: {
    flexDirection: 'row',
    gap: 10,
  },
  trackButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: dark.border,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  trackButtonActive: {
    borderColor: dark.accent,
    backgroundColor: dark.surfaceElevated,
  },
  trackEmoji: {
    fontSize: 20,
    marginBottom: 4,
  },
  trackLabel: {
    color: dark.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  trackLabelActive: {
    color: dark.accent,
  },
  trackState: {
    color: dark.textFaint,
    fontSize: 10,
    marginTop: 4,
  },
});
